version: "3.1"
services:
  backend:
    image: backend_java
    depends_on:
      - 'neo4j'
    networks:
      - neo4j_go_net
    ports:
      - 8089:8089
    restart: on-failure
  frontend:
    image: frontend_react
    depends_on:
      - 'backend'
    networks:
        - neo4j_go_net
    ports:
     - 3000:3000
  neo4j:
    image: neo4j:latest
    volumes:
      - 'data:/data'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    networks:
        - neo4j_go_net
    environment:
      NEO4J_AUTH: none
    command: neo4j
networks:
  neo4j_go_net:
    driver: bridge
volumes:
  data:
  